language: c
sudo: required
services:
  - docker
script:
  - make lint
  - make build-image
notifications:
  slack:
    secure: RcLdrlPuvvaNYPDWdKCq80jUdQsrPA8uxaAdNXC297Lq4/BZccbCPGeP9gh5fcP306GxVULgNTo/Clc86b3HnLJHe1tP4hAptPPZKBJMPP9OfdYN8pYhNtyL+rzdyON8iAI/OJXyG6eTUBMp0i+bYcHz+fhHHjzGHCAz/2ZbINby0KmYmFWaSBQYj6PDihXUEWmLNCfuzDGJNM0ipqU69RWbud52wCjG1XSXt/C1PJs8KyfAIV0XTeYnZQx3bpShksOIkQ4wbtcv8T+mBufmDxcCKTWTlBrQsCwFEn6kidEYyOsL9In8LB5esaV8SyMzUnDkbJryGl5+DHT6tYgRg7LT+q9pUZGiRZm37rx/3OHDCHNysIC6zwjvrVklaji45alA/AmDekFCO3tAIZ8aujipyqDe41AVljAnK56S7fy4yF1PAlHIDdt0Uz+rouC+BHRx3EKWSUNuFIGKFtjioS5PVy52o5uWm3hpBUIMjtDr1usJ5HFx4trhXLGIHY95v+ovZIPVd4L9FTudHhkX0+4mrBnlT9KIPuDUguHboObhw8GGaIMeiA2o8Ors+LVFycjoySNFpHz9SUcitF6QjD6edNNTlsODCOEUYPfr2uMIvD2ez8R/KZLQqPWHcd0DONFr5JqXN7QhaJHUwaP6hoYXPicZMn9M+j1Ea49Ibo0=
